# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import basic_pb2 as basic__pb2


class BasicServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Function1 = channel.unary_unary(
                '/basic_package.BasicService/Function1',
                request_serializer=basic__pb2.Request.SerializeToString,
                response_deserializer=basic__pb2.Reply.FromString,
                )


class BasicServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Function1(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Function1': grpc.unary_unary_rpc_method_handler(
                    servicer.Function1,
                    request_deserializer=basic__pb2.Request.FromString,
                    response_serializer=basic__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'basic_package.BasicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BasicService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Function1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/basic_package.BasicService/Function1',
            basic__pb2.Request.SerializeToString,
            basic__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
